// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6jiC03myrgFt7Pu1W6bIm-rrzbnQBurk',
    appId: '1:713207212853:web:2987e772f9bfd83a1c3a7c',
    messagingSenderId: '713207212853',
    projectId: 'expenser-5e899',
    authDomain: 'expenser-5e899.firebaseapp.com',
    storageBucket: 'expenser-5e899.firebasestorage.app',
    measurementId: 'G-M6NNYWSZKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxFZ20jwFDxSFdXSJPCFVqPy09DX3zGyE',
    appId: '1:713207212853:android:411f3d9082a25b5c1c3a7c',
    messagingSenderId: '713207212853',
    projectId: 'expenser-5e899',
    storageBucket: 'expenser-5e899.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5ATQImq8KC8b7IWxAiyJQ2-OHuIqVdlc',
    appId: '1:713207212853:ios:8d00350ca07f96d11c3a7c',
    messagingSenderId: '713207212853',
    projectId: 'expenser-5e899',
    storageBucket: 'expenser-5e899.firebasestorage.app',
    iosBundleId: 'com.example.expenser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5ATQImq8KC8b7IWxAiyJQ2-OHuIqVdlc',
    appId: '1:713207212853:ios:8d00350ca07f96d11c3a7c',
    messagingSenderId: '713207212853',
    projectId: 'expenser-5e899',
    storageBucket: 'expenser-5e899.firebasestorage.app',
    iosBundleId: 'com.example.expenser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6jiC03myrgFt7Pu1W6bIm-rrzbnQBurk',
    appId: '1:713207212853:web:dd4bac0ae517f2581c3a7c',
    messagingSenderId: '713207212853',
    projectId: 'expenser-5e899',
    authDomain: 'expenser-5e899.firebaseapp.com',
    storageBucket: 'expenser-5e899.firebasestorage.app',
    measurementId: 'G-1P1E2NBH4Y',
  );

}